version: '3.3'
services:
  service-chat-concept-postgres:
    container_name: chat-concept-postgres
    image: postgres:12.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - 'chat-concept:/var/lib/postgresql/data'
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_PORT}

volumes:
  chat-concept:
